version: "3.8"

services:
###Iniciar página: http://localhost:8280/ofork/index.pl
###Usuário: root@localhost
###Senha: h5vPBSBu6gWb1Cwx
  ofork:
    image: alderpinto/ofork:10.0.6
    restart: always
    ports:
#      - 443:443
      - 8280:8880
      - 8281:8881
    env_file: .env      
    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./Config.pm:/opt/otrs/Kernel/Config.pm
      - ./init:/app
      - ./app:/opt/ofork
    depends_on:
      - postgres
  postgres:
###Usuário: ofork
###Senha: VrvaN5FCbVw4EKxn  
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mjeffomybyov7xffcba6
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: