version: "3.8"

services:
###Iniciar página: http://localhost:8480/ofork/index.pl
###Usuário: root@localhost
###Senha: Yk3GDP1KZcpXgJA2
  ofork:
    image: alderpinto/ofork:11.0.1
    restart: always
    ports:
#      - 443:443
      - 8480:8880
      - 8481:8881
    env_file: .env      
    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./Config.pm:/opt/otrs/Kernel/Config.pm
      - ./init:/app
      - ./app:/opt/ofork
    depends_on:
      - postgres
  postgres:
###Usuário: ofork
###Senha: Muzv5oHawNVmgmDC  
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mjeffomybyov7xffcba6
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: